language: python
branches:
  except:
    - gh-pages
python:
  - "3.5"
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # now my stuff
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file conda_requirements.txt
  - source activate test-environment
  - conda install pytest
  - pip install coveralls
  - pip install pysis
  - pip install pytest-ipynb
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=pyciss setup.py test

after_success:
    - coveralls
    # - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aa8b92be81f54415501c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
